version: '3.9'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: Pr1mary
      POSTGRES_PASSWORD: psqldb
      POSTGRES_DB: test123
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
  migration:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db
  web:
    container_name: Api
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - URL=celery
      - TOKEN=
      - POSTGRES_HOST=db
      - POSTGRES_NAME=test123
      - POSTGRES_USER=Pr1mary
      - POSTGRES_PASSWORD=psqldb
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
  celery:
    build: .
    restart: always
    command: celery -A config worker -l info
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - web
      - db
  dashboard:
    container_name: dashboard
    build: .
    command:  celery -A config flower --address=0.0.0.0 --port=5555 broker=redis://redis:6379/0
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FLOWER_PORT=5555
    depends_on:
      - redis
      - web
      - celery