# Generated by Django 4.1 on 2022-08-20 11:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_service', '0002_alter_client_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(verbose_name='время создания рассылки')),
                ('text', models.TextField(blank=True, verbose_name='текст сообщения')),
                ('mob_codes', models.CharField(blank=True, max_length=50, verbose_name='код моб оператора')),
                ('tag', models.CharField(blank=True, max_length=50, verbose_name='метка клиента')),
                ('time_end', models.DateTimeField(verbose_name='время окончания рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile_op',
            field=models.CharField(max_length=5, verbose_name='моб оператор'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^((8|\\+7)[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}$')], verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tag',
            field=models.CharField(blank=True, max_length=100, verbose_name='метка клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='time_zone',
            field=models.CharField(choices=[('UTC-12', 'UTC-12'), ('UTC-11', 'UTC-11'), ('UTC-10', 'UTC-10'), ('UTC-9', 'UTC-9'), ('UTC-8', 'UTC-8'), ('UTC-7', 'UTC-7'), ('UTC-6', 'UTC-6'), ('UTC-5', 'UTC-5'), ('UTC-4', 'UTC-4'), ('UTC-3', 'UTC-3'), ('UTC-2', 'UTC-2'), ('UTC-1', 'UTC-1'), ('UTC', 'UTC'), ('UTC+1', 'UTC+1'), ('UTC+2', 'UTC+2'), ('UTC+3', 'UTC+3'), ('UTC+4', 'UTC+4'), ('UTC+5', 'UTC+5'), ('UTC+6', 'UTC+6'), ('UTC+7', 'UTC+7'), ('UTC+8', 'UTC+8'), ('UTC+9', 'UTC+9'), ('UTC+10', 'UTC+10'), ('UTC+11', 'UTC+11'), ('UTC+12', 'UTC+12')], max_length=6, verbose_name='часовой пояс'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('PROCEEDED', 'Proceeded'), ('FAILED', 'Failed')], max_length=15, verbose_name='Статус отправки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='API_service.client')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='API_service.mailing')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
