# Generated by Django 4.1 on 2022-08-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_service', '0003_mailing_alter_client_options_alter_client_mobile_op_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('no sent', 'No sent')], max_length=15, verbose_name='Статус отправки'),
        ),
    ]
